### ISSUE TITLE
Write first-cut predictoor docs, and link to them from app

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-web#107]
### DoD: 
- [x] Create a docs inside docs.oceanprotocol.com for the app 
  - [x] Include some "about" info
  - [x] Include some "how to" info
- [N/A] In predictoor app, make "about" button link to the docs --> moved to [pdr-web#258](https://github.com/oceanprotocol/pdr-web/issues/258)

### Background

An aside: there had been a proposal to create "how to use" info in the app itself. Please don't do that by adding lots of text to the screen. We'll do it in the docs.

We may not have time to create an onboarding experience that's embedded in the app.
Please do not try to solve this by adding text to the screen.

ie do NOT do the following
![image](https://github.com/oceanprotocol/pdr-web/assets/69865342/ce55e9ee-9e52-4007-b8f5-8f4bfc0aa845)

If we do have text in this area should be describing what predictoor is, not how to use it. It's the sizzle, not the how-to. "Accurate price predictions for your favorite crypto assets." See [#105](https://github.com/oceanprotocol/pdr-web/issues/105)

![image](https://github.com/oceanprotocol/pdr-web/assets/69865342/89df14a5-903d-4b2f-aef1-928ab6caa308)

**Comment by trentmc** [comment]
Closing this, because done except the final step, which I've created a new github issue for: https://github.com/oceanprotocol/pdr-web/issues/258
