### ISSUE TITLE
Add wheel to subscription purchase. Make feed appear right after success message.

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-web#114]
### Problem
There can be long pauses for the user as he goes through the purchase process.
During purchasing, no wheel is visible enabling him to know things are still working.

After purchasing successfully and seeing the alert, the predictions take way too long to start working.
The react components/context should be getting updated right away, rather than having to wait 60+ secs to refresh.
![image](https://github.com/oceanprotocol/pdr-web/assets/69865342/fda1884d-d5fc-469a-a2fd-b64a42d16fd0)

### DoD:
- [ ] Loading message + wheel shows inside "Buying" so user can see app is still running
- [ ] Loading message goes away + subscription active shows up right after successfully completing

**Comment by KatunaNorbert** [comment]
Update to this, I added a loading wheel at the beginning of the asset row where the subscription status dot is displayed to inform user that the action on subscription is ongoing.
Let me know If you think it is still necessary to show the wheel inside the button as well
