### ISSUE TITLE
Display number of Predictoor for a prediction

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/pdr-web#217]
In the prediction column, around the prediction, display the number of Predictoors that participated in that predicted value. A possible option is to add a tooltip after the staked amount and inside tooltip display the information.
Number of Predictoors that predicted and staked could be fetched from the Subgraph.

**Comment by trentmc** [comment]
@trizin - correct.

Here is the slack thread, for reference:
https://oceanprotocol.slack.com/archives/C05QYJMLRPD/p1695380787179389?thread_ts=1695365366.089699&channel=C05QYJMLRPD&message_ts=1695380787.179389

And, it seems in the thread that @KatunaNorbert  has acknowledged this. It was just that this ticket hasn't been closed yet. I will close it now.
