### ISSUE TITLE
predictoor.ai often doesn't load, unless a refresh is done

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-web#234]
Sometimes, I've found that if I go to predictoor.ai, it will just be a blank screen.

If I hit refresh, and it will show up.

This was on ios (iphone) + chrome.

A friend also reported the same issue, and same solution.

I think it may happen more often when people haven't been to the site before.

Regardless, this is an issue as it hurts churn, and the feeling of quality.

**Comment by KatunaNorbert** [comment]
Bug fixed here: https://github.com/oceanprotocol/pdr-web/pull/230
