### ISSUE TITLE
App crashes in Privacy Preserving browsers

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/pdr-web#241]
The app crashed with privacy-preserving browsers like Brave. I checked Posthog and the same issue occurred to others as well. See screenshot.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUVQQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ddff161eb3d047a1542a0fde5c47d1bbc20f27dc/screenshot_2023-10-05_at_20.25.27.png)

**Comment by kdetry** [comment]
It does not happen on me

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3dYQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cf3eab0bacdaf1fbd6e49f4bf023c4606d8e8cce/image.png)

**Comment by KatunaNorbert** [comment]
@andreaarmanni could you give more details on how to reproduce this issue?
