### ISSUE TITLE
Prediction Feeds are stuck, loading, after switching between 5m => 1h.

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-web#261]
### Problem
When switching to "1h", the loading wheels get stuck:
1. No past predictions
2. No current predictions
3. No current amount staked
![image](https://github.com/oceanprotocol/pdr-web/assets/69865342/697fce20-4e01-45ac-9961-7f8310a9d80d)

**Comment by KatunaNorbert** [comment]
This is caused by websocket now providing 1h timeframe data. Let's handle the issue in a more specific issue #43
