### ISSUE TITLE
Prices fetching take to much time

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/pdr-web#266]
The price fetching from Binance API takes quite a long time. In some cases when the internet connection is slow, it takes a very long time and app looks broken.
Look into how can we improve the performance of price fetching.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGszQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef679ed07156850dc0208e71c633d74d54bdc46b/Screenshot%202023-10-14%20at%2015.37.52.png)

**Comment by kdetry** [comment]
The Binance API doesn't allow fetching klines (candlestick) data for multiple symbols in a single request. You'd have to make separate requests for each symbol.

We can fetch all data in the websocket project and we can cache it. And the FE could fetch all of the pairs at one request.
It depends on our decision @idiom-bytes @KatunaNorbert
