### ISSUE TITLE
ToS checkbox is too small 

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/pdr-web#274]
ToS checkbox is too small, it's hard to click.

**Comment by KatunaNorbert** [comment]
What do you mean by to small? It looks fairly proportional with other font sizes.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejFSQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0d277c304f6cd3660a4ef29529582547b9880400/Screenshot%202023-10-19%20at%2012.42.53.png)

**Comment by KatunaNorbert** [comment]
It's easy enough for me to check it, maybe others can relate: @kdetry @idiom-bytes
