### ISSUE TITLE
Improve trader's UX

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/pdr-web#293]
Recently, we have added liquidity to an uniswap clone on sapphire:   https://sapphire.lizard.exchange/swap

We can use this to improve our trader's life, by using the uniswap SDK, so users that have ROSE in their account, but no OCEAN, can buy the feed by signing one additional tx (and our UI can make the swap)

**Comment by trentmc** [comment]
Duplicate with https://github.com/oceanprotocol/pdr-private/issues/51

So, closing this

I just updated that issue with the latest experiences
